# Generated by Django 3.2.3 on 2022-01-12 11:56

import datetime
from django.db import migrations, models
import base.storage


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Enter here the photo title.', max_length=200, verbose_name='Title')),
                ('published', models.DateTimeField(default=datetime.datetime.now, help_text='Enter here thr published date.', verbose_name='Date published')),
                ('image', models.ImageField(help_text='Upload your image here.', storage=base.storage.UUIDStorage, upload_to='images/', verbose_name='Image')),
            ],
        ),
    ]
