# Generated by Django 3.2.3 on 2022-01-12 11:56

import blog.models
import datetime
from django.db import migrations, models
import tinymce.models
import base.storage


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SocialShare",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "share_name",
                    models.CharField(
                        help_text="Enter here social share name.",
                        max_length=20,
                        verbose_name="Name",
                    ),
                ),
                (
                    "share_icon",
                    models.CharField(
                        blank=True,
                        help_text="Enter here icon name from fontawesome "
                        + "(Example: fab fa-facebook).",
                        max_length=20,
                        verbose_name="Icon",
                    ),
                ),
                (
                    "share_text",
                    models.CharField(
                        help_text="Enter here the text to be displayed in the link "
                        + "(Example: &t=New post ).",
                        max_length=200,
                        verbose_name="Text",
                    ),
                ),
                (
                    "share_url",
                    models.URLField(
                        help_text="Enter here link to social share account. "
                        + "(Example: https://www.facebook.com/sharer/sharer.php?u=)",
                        verbose_name="URL",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tag_name",
                    models.CharField(
                        help_text="Enter here the tag name.",
                        max_length=20,
                        verbose_name="Tag",
                    ),
                ),
                (
                    "tag_slug",
                    models.SlugField(
                        help_text="Enter here the link of tag (Example: photos)",
                        verbose_name="Link",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "article_title",
                    models.CharField(
                        help_text="Enter here the article title.",
                        max_length=200,
                        verbose_name="Title",
                    ),
                ),
                (
                    "article_published",
                    models.DateTimeField(
                        default=datetime.datetime.now,
                        help_text="Enter here thr published date.",
                        verbose_name="Date published",
                    ),
                ),
                (
                    "article_image",
                    models.ImageField(
                        help_text="Upload article cover here.",
                        storage=base.storage.UUIDStorage,
                        upload_to="images/",
                        verbose_name="Cover",
                    ),
                ),
                (
                    "article_content",
                    tinymce.models.HTMLField(
                        help_text="Enter here the article content.",
                        verbose_name="Article",
                    ),
                ),
                (
                    "article_slug",
                    models.SlugField(
                        default=blog.models.generate_slug,
                        help_text="Enter here the link of article (Example: happy_new_post).",
                        verbose_name="Link",
                    ),
                ),
                (
                    "article_top_posts",
                    models.BooleanField(
                        default=False,
                        help_text="Activate if you want to pin this post on the main page.",
                        verbose_name="Top",
                    ),
                ),
                (
                    "article_tags",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Select tags for this post.",
                        to="blog.Tag",
                        verbose_name="Tags",
                    ),
                ),
            ],
        ),
    ]
